---

virtualenv_path: "/home/ubuntu/.virtualenvs/blog_analytics"
git_repo: https://github.com/adamgrossman/rocketu_blog_analytics.git
project_name: rocketu_blog_analytics
project_path: "/home/ubuntu/{{ project_name }}"
nginx_server_name: "ec2-54-68-127-205.us-west-2.compute.amazonaws.com"
requirements_file: "{{ project_path }}/requirements.txt"